{
 "title": "Microservices Response Time Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Завершение продажи",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, path, job) (rate(microservices_http_response_time_seconds_bucket{path=\"order_make_payment_http\"}[5m])))",
     "legendFormat": "95th percentile / {{path}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, path, job) (rate(microservices_http_response_time_seconds_bucket{path=\"order_make_payment_http\"}[5m])))",
     "legendFormat": "median / {{path}}"
    }
   ]
  },
  {
   "title": "Добавление товара",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, path, job) (rate(microservices_http_response_time_seconds_bucket{path=\"add_order_item_https\"}[5m])))",
     "legendFormat": "95th percentile / {{path}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, path, job) (rate(microservices_http_response_time_seconds_bucket{path=\"add_order_item_https\"}[5m])))",
     "legendFormat": "median / {{path}}"
    }
   ]
  },
  {
   "title": "Открытие продажи",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, path, job) (rate(microservices_http_response_time_seconds_bucket{path=\"create_order\"}[5m])))",
     "legendFormat": "95th percentile / {{path}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, path, job) (rate(microservices_http_response_time_seconds_bucket{path=\"create_order\"}[5m])))",
     "legendFormat": "median / {{path}}"
    }
   ]
  },
  {
   "title": "Поиск товара",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, path, job) (rate(microservices_http_response_time_seconds_bucket{path=\"product-search\"}[5m])))",
     "legendFormat": "95th percentile / {{path}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, path, job) (rate(microservices_http_response_time_seconds_bucket{path=\"product-search\"}[5m])))",
     "legendFormat": "median / {{path}}"
    }
   ]
  },
  {
   "title": "Поиск клиента",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, path, job) (rate(microservices_http_response_time_seconds_bucket{path=\"get-customer-list\"}[5m])))",
     "legendFormat": "95th percentile / {{path}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, path, job) (rate(microservices_http_response_time_seconds_bucket{path=\"get-customer-list\"}[5m])))",
     "legendFormat": "median / {{path}}"
    }
   ]
  },
  {
   "title": "product sync query",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, path, job) (rate(microservices_http_response_time_seconds_bucket{path=\"catalogService.productRepo.GetUpdateProducts\"}[5m])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, path, job) (rate(microservices_http_response_time_seconds_bucket{path=\"catalogService.productRepo.GetUpdateProducts\"}[5m])))",
     "legendFormat": "median"
    }
   ]
  },
  {
   "title": "Core Metrics 14d Average",
   "type": "stat",
   "description": "Показатели по core метрикам в микросервисах. Среднее время ответа сервера",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(microservices_http_response_time_seconds_sum{instance=\"order-service.prod.svc.cluster.local:80\", job=\"order_service\", path=\"order_make_payment_http\"}[14d]))/sum(rate(microservices_http_response_time_seconds_count{instance=\"order-service.prod.svc.cluster.local:80\",job=\"order_service\",path=\"order_make_payment_http\"}[14d]))"
    },
    {
     "expr": "sum(rate(microservices_http_response_time_seconds_sum{instance=\"order-service.prod.svc.cluster.local:80\", job=\"order_service\", path=\"add_order_item\"}[14d]))/sum(rate(microservices_http_response_time_seconds_count{instance=\"order-service.prod.svc.cluster.local:80\",job=\"order_service\",path=\"add_order_item\"}[14d]))"
    },
    {
     "expr": "sum(rate(microservices_http_response_time_seconds_sum{instance=\"order-service.prod.svc.cluster.local:80\", job=\"order_service\", path=\"add_order_discount\"}[14d]))/sum(rate(microservices_http_response_time_seconds_count{instance=\"order-service.prod.svc.cluster.local:80\",job=\"order_service\",path=\"add_order_discount\"}[14d]))"
    },
    {
     "expr": "sum(rate(microservices_http_response_time_seconds_sum{instance=\"order-service.prod.svc.cluster.local:80\", job=\"order_service\", path=\"get_all_orders\"}[14d]))/sum(rate(microservices_http_response_time_seconds_count{instance=\"order-service.prod.svc.cluster.local:80\",job=\"order_service\",path=\"get_all_orders\"}[14d]))"
    },
    {
     "expr": "sum(rate(microservices_http_response_time_seconds_sum{instance=\"order-service.prod.svc.cluster.local:80\", job=\"order_service\", path=\"get_order_stats\"}[14d]))/sum(rate(microservices_http_response_time_seconds_count{instance=\"order-service.prod.svc.cluster.local:80\",job=\"order_service\",path=\"get_order_stats\"}[14d]))"
    },
    {
     "expr": "sum(rate(microservices_http_response_time_seconds_sum{instance=\"catalog-service-v2.prod.svc.cluster.local:80\", job=\"catalog_service-v2\", path=\"new-sale-product-search\"}[14d]))/sum(rate(microservices_http_response_time_seconds_count{instance=\"catalog-service-v2.prod.svc.cluster.local:80\",job=\"catalog_service-v2\",path=\"new-sale-product-search\"}[14d]))"
    },
    {
     "expr": "sum(rate(microservices_http_response_time_seconds_sum{instance=\"catalog-service-v2.prod.svc.cluster.local:80\", job=\"catalog_service-v2\", path=\"product-search\"}[14d]))/sum(rate(microservices_http_response_time_seconds_count{instance=\"catalog-service-v2.prod.svc.cluster.local:80\",job=\"catalog_service-v2\",path=\"product-search\"}[14d]))"
    },
    {
     "expr": "sum(rate(microservices_http_response_time_seconds_sum{instance=\"catalog-service-v2.prod.svc.cluster.local:80\", job=\"catalog_service-v2\", path=\"product-search-stats\"}[14d]))/sum(rate(microservices_http_response_time_seconds_count{instance=\"catalog-service-v2.prod.svc.cluster.local:80\",job=\"catalog_service-v2\",path=\"product-search-stats\"}[14d]))"
    }
   ]
  },
  {
   "title": "Core Metrics custom interval",
   "type": "stat",
   "description": "Показатели по core метрикам в микросервисах. Среднее время ответа сервера",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(microservices_http_response_time_seconds_sum{instance=\"order-service.prod.svc.cluster.local:80\", job=\"order_service\", path=\"order_make_payment_http\"}[$__interval]))/sum(rate(microservices_http_response_time_seconds_count{instance=\"order-service.prod.svc.cluster.local:80\",job=\"order_service\",path=\"order_make_payment_http\"}[$__interval]))"
    },
    {
     "expr": "sum(rate(microservices_http_response_time_seconds_sum{instance=\"order-service.prod.svc.cluster.local:80\", job=\"order_service\", path=\"add_order_item\"}[$__interval]))/sum(rate(microservices_http_response_time_seconds_count{instance=\"order-service.prod.svc.cluster.local:80\",job=\"order_service\",path=\"add_order_item\"}[$__interval]))"
    },
    {
     "expr": "sum(rate(microservices_http_response_time_seconds_sum{instance=\"order-service.prod.svc.cluster.local:80\", job=\"order_service\", path=\"add_order_discount\"}[$__interval]))/sum(rate(microservices_http_response_time_seconds_count{instance=\"order-service.prod.svc.cluster.local:80\",job=\"order_service\",path=\"add_order_discount\"}[$__interval]))"
    },
    {
     "expr": "sum(rate(microservices_http_response_time_seconds_sum{instance=\"order-service.prod.svc.cluster.local:80\", job=\"order_service\", path=\"get_all_orders\"}[$__interval]))/sum(rate(microservices_http_response_time_seconds_count{instance=\"order-service.prod.svc.cluster.local:80\",job=\"order_service\",path=\"get_all_orders\"}[$__interval]))"
    },
    {
     "expr": "sum(rate(microservices_http_response_time_seconds_sum{instance=\"order-service.prod.svc.cluster.local:80\", job=\"order_service\", path=\"get_order_stats\"}[$__interval]))/sum(rate(microservices_http_response_time_seconds_count{instance=\"order-service.prod.svc.cluster.local:80\",job=\"order_service\",path=\"get_order_stats\"}[$__interval]))"
    },
    {
     "expr": "sum(rate(microservices_http_response_time_seconds_sum{instance=\"catalog-service-v2.prod.svc.cluster.local:80\", job=\"catalog_service-v2\", path=\"new-sale-product-search\"}[$__interval]))/sum(rate(microservices_http_response_time_seconds_count{instance=\"catalog-service-v2.prod.svc.cluster.local:80\",job=\"catalog_service-v2\",path=\"new-sale-product-search\"}[$__interval]))"
    },
    {
     "expr": "sum(rate(microservices_http_response_time_seconds_sum{instance=\"catalog-service-v2.prod.svc.cluster.local:80\", job=\"catalog_service-v2\", path=\"product-search\"}[$__interval]))/sum(rate(microservices_http_response_time_seconds_count{instance=\"catalog-service-v2.prod.svc.cluster.local:80\",job=\"catalog_service-v2\",path=\"product-search\"}[$__interval]))"
    },
    {
     "expr": "sum(rate(microservices_http_response_time_seconds_sum{instance=\"catalog-service-v2.prod.svc.cluster.local:80\", job=\"catalog_service-v2\", path=\"product-search-stats\"}[$__interval]))/sum(rate(microservices_http_response_time_seconds_count{instance=\"catalog-service-v2.prod.svc.cluster.local:80\",job=\"catalog_service-v2\",path=\"product-search-stats\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Response Time Of Microservices / Median",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(microservices_http_response_time_seconds_bucket[$__interval])) by (le, job, path))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time Of Microservices / 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(microservices_http_response_time_seconds_bucket[$__interval])) by (le,path,job))",
     "legendFormat": "95th percentile / {{path}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(microservices_http_response_time_seconds_bucket[$__interval])) by (le,path,job))",
     "legendFormat": "median / {{path}}"
    }
   ]
  },
  {
   "title": "Response Time Of Microservices / 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(microservices_http_response_time_seconds_bucket[$__interval])) by (le, job, path))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}